apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "agent.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "agent.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "agent.fullname" . }}-webhook-cert
  dnsNames:
  - {{ include "agent.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "agent.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "agent.fullname" . }}-selfsigned-issuer
    kind: Issuer
